### ISSUE TITLE
Latero frozen after 5-10 min

### ISSUE THREAD

**Issue by hyyao** [Motsai/latero#2] opened 2016-07-01 20:55 UTC
From Xuan:

There's nothing special in operation, the basic tests with the line command, such as:
./client --latero_ip=192.168.87.98 -t 4

If you ran it again and again, it stopped by itself, sometimes in 2 minutes, sometimes 5 minutes. But in a 10 minutes running, it's almost a SURE of death.

**Comment by vlevesque** [comment] 2016-07-01 22:17
Juan's description is accurate. The software freezes after running from anywhere between 30 seconds and 8 minutes. This happens with Motsai's client in continuous mode (see Xuan's command) as well as my own software, which uses the same code for low level communication.

The output of the client app is as follows:

> Init Connection: OK.
> Please orient the Latero such that its cable is to the left.
> Sending
> printing
> pkt.magic=0xCA (Valid)
> pkt.version=0x11
> pkt.type=0x81
> pkt.seq=0x7FFF
> pkt->fullr.dio_in=0x0000
> pkt->fullr.ctrlstatus=0x0224
>   Controller Details
>   FPGA Version 2, Rev 2
>   High Voltage State : ACTIVE
>   Active Page : 0
> pkt->fullr.iostatus=0x0220
>   LateroIO Details
>   FPGA Version 2, Rev 2
>   Quadrature Decoder Error Mask = 0
> pkt->fullr.quad[0]=0x00000000 (0)
> pkt->fullr.quad[1]=0x00000000 (0)
> pkt->fullr.quad[2]=0x00000000 (0)
> pkt->fullr.quad[3]=0x00000000 (0)
> pkt->fullr.adc[0]=0x0001 (0.000 Volts)
> pkt->fullr.adc[1]=0xFFFC (-0.001 Volts)
> pkt->fullr.adc[2]=0x0000 (0.000 Volts)
> pkt->fullr.adc[3]=0xFFFF (-0.000 Volts)

I tried to update the firmware to the latest version available in GIT (2.2.6) and the problem is still present.

I haven't been able to find a workaround that eliminates the problem. Reducing the update rate as low as 250 Hz has no effect. The software still crashes often even if it is run in 30 second increments.

**Comment by acourt** [comment] 2016-07-20 15:19
Will be working on this this week. Stay tuned for a patch to the firmware.

**Comment by jsamch** [comment] 2016-08-26 20:16
This issue is now fixed with a newly rebuilt IP layer.  Firmware is being tested for release shortly and should not hang the Latero (tested up to 4M packets as part of the release process).

**Closed as completed** 2016-08-31 01:48 UTC
Labels: bug
